# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- PoC/net

pool:
  vmImage: windows-latest

steps:
- task: CmdLine@2
  inputs:
    script: 'pwsh bin/Debug/net5.0/playwright.ps1 install'
# - task: VSTest@2
#   inputs:
#     testSelector: 'testAssemblies'
#     testAssemblyVer2: |
#       **\*Tests*.dll
#       !**\*TestAdapter.dll
#       !**\obj\**
#       !**\bin\**\ref\**
#       **\PoC2.dll
#     searchFolder: '$(System.DefaultWorkingDirectory)'
- task: CmdLine@2
  inputs:
    script: 'dotnet test -l trx'
    failOnStderr: true
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '**/TestResults/*.xml'
    mergeTestResults: true
    failTaskOnFailedTests: true