# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- PoC/net

pool:
  vmImage: windows-latest

steps:
- task: CmdLine@2
  inputs:
    script: 'pwsh bin/Debug/netX/playwright.ps1 install'
- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: '**\PoC2.dll'
    searchFolder: '$(System.DefaultWorkingDirectory)'
