# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- PoC/net

pool:
  vmImage: windows-latest

steps:
- task: CmdLine@2
  displayName: Intall playwright
  inputs:
    script: 'pwsh bin/Debug/net5.0/playwright.ps1 install'
- task: CmdLine@2
  displayName: Run tests
  inputs:
    script: 'dotnet test -l trx'
- task: PublishTestResults@2
  displayName: Publish test results
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '**/TestResults/*.trx'
    mergeTestResults: true
    failTaskOnFailedTests: true